### ISSUE TITLE
Exported HTML broken for this sample data set

### ISSUE THREAD

**Issue by pkgw** [aperiosoftware/aas-timeseries#48]
Discovered by @gregschwarz. Save [this file](https://github.com/aperiosoftware/aas-timeseries/files/4149172/osand.csv.txt) under the name `osand.csv`. Then, in a Jupyter notebook:

```python
from astropy.time import Time
from astropy.timeseries import TimeSeries
from astropy.utils.data import get_pkg_data_filename

sampled_filename = get_pkg_data_filename('osand.csv')
ts = TimeSeries.read(sampled_filename, format='ascii',time_column='JD',time_format='jd')

from aas_timeseries import InteractiveTimeSeriesFigure
fig = InteractiveTimeSeriesFigure()
fig.add_markers(time_series=ts, column='Mag', label='V band magnitude')
fig.preview_interactive()

fig.save_static('my_figure', format='pdf')
fig.export_interactive_bundle('my_figure.zip')
```

The interactive view in the the notebook is fine, and the static figure is fine, but the HTML export is busted:

![Screenshot from 2020-02-03 12-28-35](https://user-images.githubusercontent.com/59598/73675599-be425d80-4680-11ea-8a51-5933301f4f8c.png)

**Comment by pkgw** [comment]
The files within the bundle look fine. I think one of the script files hosted at `aperiosoftware.github.io` may have gotten broken?

**Comment by augustfly** [comment]
It may or may not be relevant but if you click into the figure the dot follows the cursor: https://authortools.aas.org/my_figure/

**Comment by astrofrog** [comment]
@augustfly - I don't see an issue in https://authortools.aas.org/my_figure/ - this is what I see, and panning works as expected:

![Screenshot from 2020-02-04 15-13-35](https://user-images.githubusercontent.com/314716/73757312-f751ff00-4760-11ea-8cf0-ac13a56ed92a.png)

Are you still seeing an issue, and if so what browser are you using? Can you send a video/GIF?

Investigating the original issue now.

**Comment by augustfly** [comment]
@astrofrog they updated that version to use a rolled back timeseries.js to make it work (commit 99b8e44d80e1e9a06af30d501f0c541d8d2f8d0c of PR #70).

**Comment by astrofrog** [comment]
Ok thanks - bisecting indicates the following commit as the problem: https://github.com/aperiosoftware/timeseries.js/commit/3170bdef42d26931629fd0cb632c4fe6f977b785

**Comment by astrofrog** [comment]
@pkgw @augustfly - this should be fixed in aas-timeseries v0.1b4 - can you confirm? (please re-open if not)

For now the fix was to release a stable version of the JS code prior to the last merged PR which broke some use cases, and the recommended ``<script>`` for HTML files is now a single line:

```html
   <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/releases/timeseries-0.1.0.js"></script>
```

Instead of the seven ones that were there before (for CSS and JS). The template in aas-timeseries has been updated to use this. If you have existing other figures you made, I'd recommend getting rid of:

```html
  <link rel="stylesheet" href="https://aperiosoftware.github.io/timeseries.js/resources/aas.css">
  <link rel="stylesheet" href="https://aperiosoftware.github.io/timeseries.js/resources/style.css">
  <link rel="stylesheet" href="https://aperiosoftware.github.io/timeseries.js/resources/timeseries.css">
  <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/resources/big.min.js"></script>
  <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/resources/stuquery.js"></script>
  <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/resources/graph.js"></script>
  <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/resources/timeseries.js"></script>
```

and replacing it with:

```html
   <script language="javascript" type="text/javascript" src="https://aperiosoftware.github.io/timeseries.js/releases/timeseries-0.1.0.js"></script>
```

**Comment by pkgw** [comment]
Can confirm that things are working again if I use the package from git `master`. Should it be straightforward to get a new release made?

**Comment by astrofrog** [comment]
I already made a new release (1.0b4) - let me know if that doesn't work!

**Comment by augustfly** [comment]
I can confirm that 

`pip install aas-timeseries==0.1b4`

produces a version that loads on a proper webserver:

http://authortools.aas.org/gus_figure/
